version: "3.8"

services:
  # ───────────────────────────────────────── n8n ─────────────────────────────────────────
  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Asia/Kolkata
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=adminpass
    volumes:
      - ./n8n/.n8n:/home/node/.n8n        # persistent credentials / workflows
    depends_on:
      - postgres
    restart: unless-stopped

  # ──────────────────────────────────────── Postgres ──────────────────────────────────────
  postgres:
    image: postgres:14
    container_name: compass_postgres
    environment:
      POSTGRES_USER: compass_user
      POSTGRES_PASSWORD: compass_pass
      POSTGRES_DB: compass_db
    ports:
      - "5432:5432"
    volumes:
      - ./infra/pgdata:/var/lib/postgresql/data   # durable data
    restart: unless-stopped

  # ───────────────────────────────────────── Backend ──────────────────────────────────────
  backend:
    build:
      context: ./backend            # expects backend/Dockerfile
    container_name: compass_backend
    ports:
      - "8000:8000"                 # FastAPI exposed here
    volumes:
      # hot-reload code during dev; mount only the app folder
      - ./backend/app:/usr/src/app/app
    environment:
      # later you’ll add DB connection & supabase keys here
      - PYTHONUNBUFFERED=1
    depends_on:
      - postgres
    restart: unless-stopped
