version: "3.8"
services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    volumes:
      - ./n8n/.n8n:/home/node/.n8n
    environment:
      - GENERIC_TIMEZONE=Asia/Kolkata
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=adminpass
    restart: unless-stopped

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: compass_user
      POSTGRES_PASSWORD: compass_pass
      POSTGRES_DB: compass_db
    ports:
      - "5432:5432"
    volumes:
      - ./infra/pgdata:/var/lib/postgresql/data
